# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  desktop:
    taskfile: ./desktopApp
    flatten: true
  ios:
    taskfile: ./iosApp
    flatten: true
  android:
    taskfile: ./androidApp
    flatten: true

tasks:
  invalidate-cache:
    cmds:
      - rm -rf .gradle
      - rm -rf .idea
      - task: clean:all
      - rm -rf .kotlin
  clean:
    cmds:
      - rm -rf build
  clean:all:
    cmds:
      - task: clean
      - task: desktop:clean
      - task: ios:clean
      - task: android:clean

  setup:spotless:
    cmds:
      - git config core.hooksPath .githooks
      - chmod +x .githooks/pre-commit
      - echo "Installed Spotless pre-commit hook (.githooks/pre-commit)"
  setup:prettier:
    cmds:
      - node --version
      - npm --version
      - ./gradlew spotlessCheck
  spotless:
    cmds:
      - ./gradlew spotlessApply
