# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app
    flatten: true
  firebase:
    taskfile: ./firebase/Taskfile.yml
    dir: ./firebase

tasks:
  format:
    desc: "Run code formatters (Spotless for Kotlin/Gradle, Prettier for JSON/YAML/Markdown/JS)"
    cmds:
      # - task: spotless
      - npx prettier --write .

  format:check:
    desc: "Verify code formatting without applying changes"
    cmds:
      # - task: spotless:check
      - npx prettier --check .
