# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  android:clean:
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - ./gradlew clean
  android:alpha:release:
    cmds:
      - ./gradlew :androidApp:assembleAlphaRelease
      - 'echo "Output folder: androidApp/build/outputs/apk/alpha/release/androidApp-alpha-release.apk"'
    generates:
      - androidApp/build/outputs/apk/alpha/release/androidApp-alpha-release.apk
