-dontwarn org.graalvm.nativeimage.hosted.**
-dontwarn com.oracle.svm.core.annotate.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-dontwarn okhttp3.internal.graal.**
-dontwarn okhttp3.internal.platform.**
-keep class org.sqlite.** { *; }
