# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  desktop:clean:
    cmds:
      - ./gradlew clean
  desktop:darwin:
    cmds:
      - ./gradlew :desktopApp:packageDmg --console=plain
      - 'echo "Output folder: desktopApp/build/compose/binaries/main/dmg"'
      - find desktopApp/build -type f -name "*.dmg"
  desktop:windows:
    cmds:
      - ./gradlew :desktopApp:packageMsi --console=plain
      - 'echo "Output folder: desktopApp/build/compose/binaries/main/msi"'
      - find desktopApp/build -type f -name "*.msi"
  desktop:linux:
    cmds:
      - ./gradlew :desktopApp:packageDeb --console=plain
      - 'echo "Output folder: desktopApp/build/compose/binaries/main/deb"'
      - find desktopApp/build -type f -name "*.deb"
  desktop:darwin:release:
    cmds:
      - ./gradlew :desktopApp:packageReleaseDmg --console=plain
      - 'echo "Output folder: desktopApp/build/compose/binaries/main-release/dmg"'
      - find desktopApp/build -type f -name "*.dmg"
  desktop:windows:release:
    cmds:
      - ./gradlew :desktopApp:packageReleaseMsi --console=plain
      - 'echo "Output folder: desktopApp/build/compose/binaries/main-release/msi"'
      - find desktopApp/build -type f -name "*.msi"
  desktop:linux:release:
    cmds:
      - ./gradlew :desktopApp:packageReleaseDeb --console=plain
      - 'echo "Output folder: desktopApp/build/compose/binaries/main-release/deb"'
      - find desktopApp/build -type f -name "*.deb"
